### ISSUE TITLE
Can't use module on CWP platform

### ISSUE THREAD

**Issue by robbieaverill** [bringyourownideas/silverstripe-maintenance#113]
When trying to run the report generation task on the CWP platform we get this error in the failed job output:

```
[2018-06-25 15:03:04][INFO] Job caused exception The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly in /sites/training-uat/releases/20180625025533/vendor/composer/composer/src/Composer/Factory.php at line 648
```

@sminnee suggested that he'd fixed the same error on the addons site by defining COMPOSE_HOME as one of your project variables in platform configuration, though for a default CWP site we'd rather define a fallback in code if it's not defined already, e.g.

```php
if (!Environment::getEnv('COMPOSER_HOME')) {
    Environment::setEnv('COMPOSER_HOME', '/tmp');
}
```

Needs testing too of course

## Pull requests

- [x] #114 
- [x] https://github.com/silverstripe/cwp/pull/125
- [x] https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/35
- [x] https://github.com/bringyourownideas/silverstripe-maintenance/pull/115
- [x] https://github.com/silverstripe/cwp/pull/127
- [x] https://github.com/silverstripe/cwp/pull/128

Tested on CWP and SSP

**Comment by sminnee** [comment]
Give it a god, but not sure if this will work as this would rely on `putenv()` to pass the variable to composer, which seems to fail intermittently.

**Comment by brynwhyman** [comment]
Is this issue relevant to SSP as well?

**Comment by robbieaverill** [comment]
Yep, just tested

**Comment by robbieaverill** [comment]
`Environment::setEnv/putEnv` doesn't carry through, but `putenv` works

**Comment by robbieaverill** [comment]
Ok, now hitting a blocker with the CWP proxy (related: https://github.com/silverstripe/silverstripe-cms/issues/2168).

Will need to see if we can inject this config somehow

**Comment by NightJar** [comment]
Nice work!

**Comment by NightJar** [comment]
I'd like to also point out that while we've achieved resolution in the context of which we are testing, I think this issue spans wider than just CWP (or the recipe of such at least), indicated in the fact that it also affected SSP - and while it works again now, it's because we're testing it in the context of a CWP recipe.

The fix:
https://github.com/silverstripe/cwp/blob/3ad235e1286939a5291a911c602ca42907b1746c/src/Extensions/MaintenanceProxyExtension.php#L29
Resides in `cwp/cwp`

Meaning anyone _not_ using CWP (at least the module, but in the broader sense the platform as a whole) will still be affected by this exception any time they attempt to retrieve the task list (or run the task itself) from a user that does not have these environment variables set.

However if I were betting inclined, I'd wager that this will affect _any_ web server that runs as it's own user - typically a non-login user meaning an absence any _profile_ setup files... and in many a case it's a _system_ user (UID lower than 1000) which can also mean there is no `$HOME` set either.

Exemplified in the virtual environment I was finally able to recreate this issue; there was nothing special about it's setup that I would consider unusual.

At this point I'd like to suggest moving this environment variable check to that in which the exception manifests - `bringyourownideas/silverstripe-composer-update-checker`.

**Comment by robbieaverill** [comment]
Sure, I'll do that

**Comment by NightJar** [comment]
Ideal, all done! Thanks @robbieaverill

**Comment by robbieaverill** [comment]
I've merged all the branches up.

**Comment by robbieaverill** [comment]
Tested CWP 1.9 and 2.1 on CWP platform, all good!

**Comment by robbieaverill** [comment]
Whoops, the task doesn't run in 1.9 on CWP

**Comment by robbieaverill** [comment]
Falsy, forgot to deploy the updated 1.9 CWP code 🤦‍♂️
