### ISSUE TITLE
Display any available security notifications

### ISSUE THREAD

**Issue by be2n** [bringyourownideas/silverstripe-maintenance#39]
As a Product Owner
I want to be alerted about module security issues
So that I can make more timely remedial action 

## Acceptance criteria

- If there is available security information (e.g. a new security patch) an alert is visible that summarises the information
- Security information available for individual modules is presented at a module level

Designs: https://projects.invisionapp.com/share/ASGU6A7RT8U#/screens/291050684

**Comment by clarkepaul** [comment]
There is limited design guidance provided on this issue, so before starting dev on this issue, come up with the main examples for which we would want to display an alert. The ability to have an icon within the alert probably doesn't exist in CMS/core so that can be left off for now.

Examples of when to display the alert:
If there are any security vulnerabilities
If we detect modules which are not stable?

**Comment by clarkepaul** [comment]
We are a taking a simplified approach in V3 because there are no badges in the UI that we can utilise—so we have created a single coloured badge to minimise effort required. Refer to the bottom of the designs for how to implement this in SS3. 

Within SilverStripe 4 we can utilise a wider range of colours to indicate danger/warning etc.

**Comment by NightJar** [comment]
PRs at:
https://github.com/bringyourownideas/silverstripe-composer-security-checker/pull/34
https://github.com/bringyourownideas/silverstripe-maintenance/pull/72

**Comment by robbieaverill** [comment]
All merged
